version: '3'
services:
  db:
    image: postgres:11.5
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 8000:8080

  app:
    build: .
    volumes: 
      - ".:/app"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
